config/routes.rb
Rails.application.routes.draw do
  resources :officeworks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/officework.rb
class Officework < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/officeworks_controller.rb
class OfficeworksController < ApplicationController
  before_action :set_officework, only: %i[ show edit update destroy ]

  # GET /officeworks or /officeworks.json
  def index
    @officeworks = Officework.all
  end

  # GET /officeworks/1 or /officeworks/1.json
  def show
  end

  # GET /officeworks/new
  def new
    @officework = Officework.new
  end

  # GET /officeworks/1/edit
  def edit
  end

  # POST /officeworks or /officeworks.json
  def create
    @officework = Officework.new(officework_params)

    respond_to do |format|
      if @officework.save
        format.html { redirect_to officework_url(@officework), notice: "Officework was successfully created." }
        format.json { render :show, status: :created, location: @officework }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @officework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /officeworks/1 or /officeworks/1.json
  def update
    respond_to do |format|
      if @officework.update(officework_params)
        format.html { redirect_to officework_url(@officework), notice: "Officework was successfully updated." }
        format.json { render :show, status: :ok, location: @officework }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @officework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /officeworks/1 or /officeworks/1.json
  def destroy
    @officework.destroy

    respond_to do |format|
      format.html { redirect_to officeworks_url, notice: "Officework was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_officework
      @officework = Officework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def officework_params
      params.require(:officework).permit(:name, :age, :gender, :designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/officeworks_helper.rb
module OfficeworksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/officeworks/_form.html.erb
<%= form_with(model: officework) do |form| %>
  <% if officework.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(officework.errors.count, "error") %> prohibited this officework from being saved:</h2>

      <ul>
        <% officework.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :designation, style: "display: block" %>
    <%= form.text_field :designation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/officeworks/_officework.html.erb
<div id="<%= dom_id officework %>">
  <p>
    <strong>Name:</strong>
    <%= officework.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= officework.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= officework.gender %>
  </p>

  <p>
    <strong>Designation:</strong>
    <%= officework.designation %>
  </p>

</div>

app/views/officeworks/edit.html.erb
<h1>Editing officework</h1>

<%= render "form", officework: @officework %>

<br>

<div>
  <%= link_to "Show this officework", @officework %> |
  <%= link_to "Back to officeworks", officeworks_path %>
</div>

app/views/officeworks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Officeworks</h1>

<div id="officeworks">
  <% @officeworks.each do |officework| %>
    <%= render officework %>
    <p>
      <%= link_to "Show this officework", officework %>
    </p>
  <% end %>
</div>

<%= link_to "New officework", new_officework_path %>

app/views/officeworks/new.html.erb
<h1>New officework</h1>

<%= render "form", officework: @officework %>

<br>

<div>
  <%= link_to "Back to officeworks", officeworks_path %>
</div>

app/views/officeworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @officework %>

<div>
  <%= link_to "Edit this officework", edit_officework_path(@officework) %> |
  <%= link_to "Back to officeworks", officeworks_path %>

  <%= button_to "Destroy this officework", @officework, method: :delete %>
</div>